@startuml Reliant_Notifications_v4
skinparam packageStyle rectangle
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 40
skinparam ranksep 60
hide empty members

package "SharedKernel" #F5F5F5 {

    package "shared.domain" {
        abstract class AuditableModel {
            - id: Long
            - createdAt: Instant
            - updatedAt: Instant
        }
        abstract class AuditableAbstractAggregateRoot {
            + registerEvent(event: Object): void
            + clearDomainEvents(): void
        }
        AuditableModel <|-- AuditableAbstractAggregateRoot

    }

}

package "Notifications" #EDE7F6 {

    package "interfaces" {
        class AlertController <<REST>>
        class NewsletterController <<REST>>
        AlertController ..> AlertCommandServiceImpl
        NewsletterController ..> NewsletterPort
        NewsletterController ..> NewsletterSubscription
        AlertCommandServiceImpl ..> AlertRepository
        AlertCommandServiceImpl ..> NotificationPreferenceRepository
        NewsletterController ..> NewsletterSubscriptionRepository
    }
}

AuditableAbstractAggregateRoot <|-- Alert
AuditableAbstractAggregateRoot <|-- NotificationPreference
AuditableAbstractAggregateRoot <|-- NewsletterSubscription

@enduml
